### ISSUE TITLE
Inconsistent Python Versions Supported

### ISSUE THREAD

**Issue by 09tangriro** [gakonst/pyrevm#9]
There is an inconsistency in the `pyproject.toml` file. Line 3 states the project requires `python>=3.7`, which is also reflected in the PyPi, but the actual tool dependencies on line 17 states the project requires `python^3.10`. This means the package can't be installed if you have a python version less than 3.10:
```bash
➜  pyrevm git:(master) pyenv global 3.9
➜  pyrevm git:(master) poetry env use 3.9

The specified Python version (3.9.10) is not supported by the project (^3.10).
Please choose a compatible version or loosen the python constraint specified in the pyproject.toml file.
➜  pyrevm git:(master)
```

I therefore propose the following `pyproject.toml` file:

```toml
[tool.poetry.dependencies]
python = ">=3.7"
maturin = "^0.13.5"
pytest = "^7.1.3"
```
